### PR TITLE
CA-223084: Only register SMAPIv1 adapters for SMAPIv1 plugins

### PR DESCRIPTION
**Pull request by jonludlam**
Signed-off-by: Jon Ludlam jonathan.ludlam@citrix.com

### CODE REVIEW

**Comment by lindig** [comment]
Would like to see more commits like this! Close to perfect.

**Comment by robhoes** [comment]
Stunning. But why does it work?

**Comment by jonludlam** [comment]
The original code was ensuring that only plugins registered on the master (and thus put into the SM table in the db) got registered on slaves. Unfortunately after SMAPIv3 plugins are registered on the master, when the slave restarts this code was starting up SMAPIv1 adapters for _all_ SM plugins in the database, including the SMAPIv3 ones.

**Comment by robhoes** [comment]
So was the list filter on the version not working? Do v3 plugins not have the correct version in the db?

**Comment by jonludlam** [comment]
The version number is under the control of the plugin.

**Comment by robhoes** [comment]
Ok, so sounds like this is the best we can do, and have to assume that all hosts in the pool have the same plugins installed.

**Pull request merged**
