### PR TITLE
[HFX-1504/Amelie]CA-176934: Fix race in DP.destroy

### PR DESCRIPTION
**Pull request by koushikcgit**
Fix race in DP.destroy

Signed-off-by: Jon Ludlam jonathan.ludlam@citrix.com

### CODE REVIEW

**Comment by koushikcgit** [comment]
Backport of https://github.com/xapi-project/xen-api/pull/2294

**Comment by koushikcgit** [comment]
@jonludlam  Can you review this HFX please?

**Comment by jonludlam** [comment]
looks ok to me - did you have to do any fixups, or did it just rebase nicely?

**Comment by koushikcgit** [comment]
@jonludlam It applied cleanly

**Pull request merged**
