### PR TITLE
Reduce redundancy in gen_cmds function in cli_operations.ml

### PR DESCRIPTION
**Pull request by lindig**
This commit addresses a code smell and low entropy in the code. It does not change semantics. I believe a refactoring could go further but this is a start.
- Remove redundant parentheses around functions
- Use Module.() syntax to cut down use of long qualified names
- Use List.concat rather than repeatedly (@) to improve readability and efficiency

Signed-off-by: Christian Lindig christian.lindig@citrix.com

### CODE REVIEW

**Comment by robhoes** [comment]
I don't really mind this, as long as you can prove that it hasn't changed anything...

**Comment by lindig** [comment]
I can't prove it and by this token, I better start firing up Coq. But before and after we have 34 entries and so I haven't dropped one. And I think we can agree that `List.concat [a; b; c] == a @ b @ c @ []`, which is behind the move to `List.concat`. We probably can also agree that `(f) == f` - dropping parentheses around names doesn't change them. This leaves the use of `M.( )` to avoid using `M.x` repeatedly.

**Comment by robhoes** [comment]
I don't object to the kind of transformations. I'm just a little worried that some of the strings may have been changed, which subtly changes something. This is very hard to verify in the diff.

**Comment by lindig** [comment]
I'm pretty confident that both revisions contain the same strings in the same order:

```
:xapi $ git show HEAD~:./cli_operations.ml | grep -o '"[^"]*"' > old
:xapi $ git show HEAD:./cli_operations.ml | grep -o '"[^"]*"' > new
:xapi $ diff old new
:xapi $ wc old new
    1742    3412   27199 old
    1742    3412   27199 new
    3484    6824   54398 total
```

**Comment by robhoes** [comment]
Cool, that's the kind of "proof" I was looking for. Thanks and :shipit:!

**Pull request merged**
