### PR TITLE
Ely merge

### PR DESCRIPTION
**Pull request by gaborigloi**
Merge of bugfixes from master to Ely branch.

### CODE REVIEW

**Comment by lindig** [comment]
Could you expand the commit message? I'm a bit puzzled to see commits from many different issues being merged here. I guess it has to do with the branching but I'd value some more context.

**Comment by gaborigloi** [comment]
@lindig I'm not yet familiar with how we do branching either, so @jonludlam is the best person to ask, because he showed me how to perform the branching.
We based this ely-bugfix branch on the latest xapi release, [v1.13.0](https://github.com/xapi-project/xen-api/releases/tag/v1.13.0). In this pull request we collected the newer commits we need, in this case these are all the commits between the v1.13.0 release and `master` (we rebased to remove the merge commits), these are all `mustfix` issues.

**Comment by lindig** [comment]
After having talked to @jonludlam: These are commits from master that are now going into the Ely via this `ely-bugfix`.

**Comment by gaborigloi** [comment]
Thanks for clarifying this, I'll note down a few additional things here:
Now that Ely has branched, we have to manually get the commits into it by sending a pull request to here. This branch is automatically synchronized with our local

**Pull request merged**
