### PR TITLE
CA-237543: Move management to new VLAN PIF on a Bond.create/destroy

### PR DESCRIPTION
**Pull request by sharady**
If Management VLAN exists on a bond member pif then:
1) Move the IP configuration to new vlan pif.
2) Move the management to the new vlan pif.
3) Skip `bring_pif_down call for old vlan pif.

Move the management from old vlan pif to new vlan pif
before bringing up the Bond PIF. In order to keep the vlan bridge
up during bond.create

Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>

### CODE REVIEW

**Comment by sharady** [comment]
Needs https://github.com/xenserver/xcp-networkd/pull/14

**Comment by robhoes** [comment]
@sharady Do you not need to handle the destroy case separately?

**Comment by sharady** [comment]
Doesn't come out any issue while testing it, Is there any issue you can foresee?
I have tested bond.destroy for single host - it came out fine.
Lemme test same on slave too, I think we might need some tweaks there.

**Comment by robhoes** [comment]
Similar to Bond.create. When the slaves are plugged, new bridges are create for them, and the bond bridge is destroyed. If there was as a VLAN on it, then it will be destroyed as well. VLANs are moved only after that.

**Comment by sharady** [comment]
Indeed there was a similar problem on slave during bond.destroy, Fixed it with matching code as bond.create
@robhoes please have a look now.

**Review by robhoes — APPROVED** [review]

**Pull request merged**
