### PR TITLE
[HFX-1510/Amelie] CA-166748: cleanup SXM after XAPI restart

### PR DESCRIPTION
**Pull request by koushikcgit**

### CODE REVIEW

**Comment by koushikcgit** [comment]
Hi @johnelse : Can you have a check on this now?

**Comment by johnelse** [comment]
Backport of xapi-project#2326

**Comment by koushikcgit** [comment]
@johnelse Thanks - I have reworked based on your comments

**Comment by johnelse** [comment]
Looks good, thanks!

**Pull request merged**
