### PR TITLE
[HFX-1510/Amelie] CA-166748: cleanup SXM after XAPI restart

### PR DESCRIPTION
**Pull request by koushikcgit**

### CODE REVIEW

**Comment by koushikcgit** [comment]
added @johnelse  and @jonludlam  as reviewers

**Comment by johnelse** [comment]
Backport of https://github.com/xapi-project/xen-api/pull/2326

**Comment by johnelse** [comment]
I notice a few places where code changes are not in the same commit they were in the original pull request; also the commits are not in the same order. These two things are probably related :-)

I recommend cherry-picking the commits in the same order they were in on the original branch. Note, this is not necessarily the order they are shown in on the pull request page (which is annoying).

**Comment by koushikcgit** [comment]
Superseded by https://github.com/xenserver/xen-api/pull/41

**Pull request closed without merging**
