### PR TITLE
CP-12946: Start using VDB backend-kind in preparation for upgrade to 6.5

### PR DESCRIPTION
**Pull request by koushikcgit**

### CODE REVIEW

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by sharady** [comment]
@xen-git test this please

**Comment by simonjbeaumont** [comment]
Commits might need picking from Cream rather than trunk and also the final commit needs to be replaced with the original commit that introduced this key.

**Comment by simonjbeaumont** [comment]
Also we should rename this pull request (and the ticket title) to be more descriptive.

**Comment by koushikcgit** [comment]
@simonjbeaumont : Updated

**Comment by simonjbeaumont** [comment]
Can you test this on an installation of `clearwater-sp1-bugfix`? The test to do is to install a VM and start it. You can then see the metadata that Xenopsd has for the VBD by looking on the filesystem at

```
/var/run/nonpersistent/xenops/VM/<vm-uuid>/vbd.xvda
```

This should be json and you can confirm that the `backend-kind` key doesn't exist in the `extra_backend_keys` dictionary.

Then can you (with the VM still running) set the `backend-kind` key on the VBD:

```
xe vbd-param-set uuid=<vbd-uuid> other-config:backend-kind=foobar
```

This won't take effect for the running VM until the updated Xenopsd metadata is pushed down. Unfortunately, updating the VBD record is not enough to cause a metadata update. Fortunately an update can be triggered by setting the name label of the VM (even if you use the existing name):

```
xe vm-param-set uuid=<vm-uuid> name-label=<name-label>
```

Now can you check the file in `/var/run` and check that the `extra_backend_keys` now contains the `backend-kind` key?

**Comment by simonjbeaumont** [comment]
@xen-git: test this please.

**Comment by koushikcgit** [comment]
@simonjbeaumont  Yes - that works!

**Comment by simonjbeaumont** [comment]
Great! :shipit:

**Pull request merged**
