### PR TITLE
CA-222047: Dont destroy the applied updates

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Phus Lu phus.lu@citrix.com

### CODE REVIEW

**Comment by lindig** [comment]
I'm not a native speaker but I'd write the error message as `The specified update has been applied and cannot be destroyed.` I noticed that `is applied` is used in the existing message above the new one. Could someone with more grammar knowledge comment?

**Comment by robhoes** [comment]
I'm not a native speaker either, but I believe that @lindig is right. Unfortunately, a native English speaker had already added the `patch_is_applied` error in 2008.

**Comment by robhoes** [comment]
Funny enough, there is a already a better version, `patch_already_applied`, below.

**Comment by lindig** [comment]
Looking at other messages, I see more questionable wording: `The patch apply failed.` This should be `The patch application failed`.

**Comment by thomassa** [comment]
It is not exactly wrong to say "The specified {update|patch} is applied and cannot be destroyed."
It would be better to have "has been" instead of "is", though.

The `patch_already_applied` error that @robhoes noticed does not have the "...and cannot be destroyed" part; it looks to me as if it would be an appropriate error to raise when someone tries to apply a patch that has been applied already. (I presume that's the case in which we raise it.)

**Comment by kc284** [comment]
With my UX hat on, I would suggest "Failed to apply the patch" - interfaces and messages should be action oriented.

**Comment by jonludlam** [comment]
I agree with @thomassa. Let's change the explanation text from 'is applied' to 'has been applied'. Let's keep the name of the exception as is though (`UPDATE_IS_APPLIED`).

**Comment by ghost** [comment]
Thanks all, I updated this PR to change 'is applied' to 'has been applied'

**Comment by thomassa** [comment]
For what it's worth, I agree with @kc284.

**Comment by lindig** [comment]
As you can see, I already merged it. But it might be worth looking at the wording of all these messages in one go and to fix them. There are more questionable ones. I also like @kc284's wording.

**Pull request merged**
