### PR TITLE
CP-18970: Convert pool_patch to pool_update

### PR DESCRIPTION
**Pull request by cheng-z**
1. Deprecate patches-requiring-reboot in host record
2. Remove update-upload
3. Convert pool_patch to pool_update

Signed-off-by: Cheng Zhang cheng.zhang@citrix.com

### CODE REVIEW

**Comment by jonludlam** [comment]
Blocked until Simon and I have a chat about this.

**Comment by GaborApatiNagy** [comment]
patches-requiring-reboot has been added for live patching, XenCenter relies on it - do we really want to deprecate this?

**Comment by jonludlam** [comment]
Ah, another interaction with live patching... :-(

**Comment by GaborApatiNagy** [comment]
@jonludlam, luckily there are not much more :)

**Comment by jonludlam** [comment]
Not the right approach, it has been decided.

**Pull request closed without merging**
